name: WallsMinigame
version: 1.0
main: com.icey.walls.MainClass
description: The Hypixel Walls Minigame
author: iceyprotato

commands:
    walls:
        usage: /<command> subcommand
        description: Walls command for version and setup.
        aliases: [wa, wl, wal, wall]
    test:
        usage: /<command> <subcommand>
        description: test command for various walls things