name: WallsMinigame
version: 1.0
main: com.icey.walls.MainClass
description: The Hypixel Walls Minigame

commands:
    walls:
        usage: /<command> subcommand
        description: Walls command for version and setup.
    test:
        usage: /<command> <subcommand>
        description: testing copying and pasting